import { getServerSession } from "next-auth"
import { authOptions } from "../auth/[...nextauth]/route"
import { Octokit } from "@octokit/rest"
import { cleanContent } from "@/lib/helpers/clean"
import type { ScanResult } from "@/lib/types/scan"

type CleanStrategy = "pr" | "main"

export async function POST(req: Request) {
  const session = await getServerSession(authOptions)
  if (!session) return Response.json({ error: "Not signed in" }, { status: 401 })

  const { owner, repo, results, strategy = "pr" } = (await req.json()) as {
    owner: string
    repo: string
    results: ScanResult[]
    strategy?: CleanStrategy
  }

  if (strategy !== "pr" && strategy !== "main") {
    return Response.json({ error: "invalid strategy" }, { status: 400 })
  }

  const octokit = new Octokit({ auth: session.accessToken })

  const { data: repoMeta } = await octokit.repos.get({ owner, repo })
  const defaultBranch = repoMeta.default_branch

  async function applyCleanToBranch(branch: string) {
    for (const result of results) {
      const { data: fileData } = await octokit.repos.getContent({
        owner,
        repo,
        path: result.file,
        ref: branch,
      })

      if (!("content" in fileData)) continue

      const content = Buffer.from(fileData.content, "base64").toString("utf-8")
      const cleaned = cleanContent(content, result.findings)
      const encoded = Buffer.from(cleaned).toString("base64")

      await octokit.repos.createOrUpdateFileContents({
        owner,
        repo,
        path: result.file,
        message: `fix: remove hardcoded secret in ${result.file}`,
        content: encoded,
        sha: fileData.sha,
        branch,
      })
    }
  }

  const bodyFooter = `

### What was changed:
- Hardcoded secrets replaced with \`process.env.VARIABLE_NAME\` references
- Add the actual values to your \`.env.local\` file

> ⚠️ Make sure to revoke and rotate any exposed secrets immediately.`

  if (strategy === "main") {
    await applyCleanToBranch(defaultBranch)
    return Response.json({
      success: true,
      mode: "main" as const,
      branch: defaultBranch,
    })
  }

  const { data: ref } = await octokit.git.getRef({
    owner,
    repo,
    ref: `heads/${defaultBranch}`,
  })
  const baseSha = ref.object.sha

  const branchName = `vaultless/clean-secrets-${Date.now()}`
  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  })

  await applyCleanToBranch(branchName)

  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    title: "fix: remove hardcoded secrets found by Vaultless",
    body: `## Vaultless Secret Scan Results

This PR was automatically generated by Vaultless.

### What was found:
${results.map((r) => `- \`${r.file}\` — ${r.findings.length} secret(s) found`).join("\n")}
${bodyFooter}`,
    head: branchName,
    base: defaultBranch,
  })

  return Response.json({
    success: true,
    mode: "pr" as const,
    prUrl: pr.html_url,
  })
}
