import { getServerSession } from "next-auth"
import { authOptions } from "../auth/[...nextauth]/route"
import { Octokit } from "@octokit/rest"
import { cleanContent } from "@/lib/helpers/clean"
import type { ScanResult } from "@/lib/types/scan"

export async function POST(req: Request) {
  const session = await getServerSession(authOptions)
  if (!session) return Response.json({ error: "Not signed in" }, { status: 401 })

  const { owner, repo, results } = (await req.json()) as {
    owner: string
    repo: string
    results: ScanResult[]
  }

  const octokit = new Octokit({ auth: session.accessToken })

  // 1. get the SHA of main branch
  const { data: ref } = await octokit.git.getRef({
    owner,
    repo,
    ref: "heads/main",
  })
  const mainSha = ref.object.sha

  // 2. create a new branch
  const branchName = `vaultless/clean-secrets-${Date.now()}`
  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: mainSha,
  })

  // 3. clean and commit each file
  for (const result of results) {
    // fetch current file content
    const { data: fileData } = await octokit.repos.getContent({
      owner,
      repo,
      path: result.file,
      ref: branchName,
    })

    if (!("content" in fileData)) continue

    const content = Buffer.from(fileData.content, "base64").toString("utf-8")
    const cleaned = cleanContent(content, result.findings)
    const encoded = Buffer.from(cleaned).toString("base64")

    // commit cleaned file
    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: result.file,
      message: `fix: remove hardcoded secret in ${result.file}`,
      content: encoded,
      sha: fileData.sha,
      branch: branchName,
    })
  }

  // 4. open a PR
  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    title: "fix: remove hardcoded secrets found by Vaultless",
    body: `## Vaultless Secret Scan Results

This PR was automatically generated by [Vaultless](https://vaultless.dev).

### What was found:
${results.map((r) => `- \`${r.file}\` — ${r.findings.length} secret(s) found`).join("\n")}

### What was changed:
- Hardcoded secrets replaced with \`process.env.VARIABLE_NAME\` references
- Add the actual values to your \`.env.local\` file

> ⚠️ Make sure to revoke and rotate any exposed secrets immediately.`,
    head: branchName,
    base: "main",
  })

  return Response.json({ prUrl: pr.html_url })
}